services/web/src/auth.py
import logging
from datetime import datetime
from datetime import timedelta

from flask import (Blueprint,
                   redirect,
                   render_template,
                   flash,
                   request,
                   url_for)
from flask_login import current_user, login_user

from . import login_manager
from .common.url import ServiceCaller
from .forms import LoginForm, SignupForm
from .models import (db,
                     Users)

# Blueprint Configuration
auth_bp = Blueprint('auth_bp', __name__,
                    template_folder='templates',
                    static_folder='static')


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in on every page load."""
    if user_id is not None:
        return Users.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view that page.')
    return redirect(url_for('auth_bp.login'))


@auth_bp.route('/notes/login', methods=['GET', 'POST'])
def login():
    """
    Log-in page for registered users.

    GET: Serve Log-in page.
    POST: Validate form and redirect user to dashboard.
    """
    if current_user.is_authenticated:
        logging.info(f'User authenticated')
        return redirect(url_for('get_all_notes', alt_id=current_user.alternative_id))  # Bypass if user is logged in

    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()  # Validate Login Attempt
        logging.info(f'USER:{user}')
        if user and user.check_password(password=form.password.data):
            logging.info(f'user_{user.id}-{user.username} is logging')
            user.last_login = datetime.now()
            db.session.commit()
            logging.info(f'last_login has been updated')
            login_user(user, remember=True, duration=timedelta(days=1))
            next_page = request.args.get('next')
            return redirect(next_page or url_for('get_all_notes', alt_id=user.alternative_id))
        flash('Invalid email/password combination')
        logging.info(f'WRONG CREDS !!! {form.email.data} was provided')
        return redirect(url_for('auth_bp.login'))
    return render_template('login.html',
                           form=form,
                           title='Log in.',
                           template='login-page',
                           body="Log in with your User account.")


@auth_bp.route('/notes/signup', methods=['GET', 'POST'])
def signup():
    """
    Sign-up form to create new user accounts.

    GET: Serve sign-up page.
    POST: Validate form, create account, redirect user to dashboard.
    """
    form = SignupForm()
    logging.info('web ::: signup ::: get called')
    if form.validate_on_submit():
        logging.info('web ::: form validated properly')
        existing_user = Users.query.filter_by(email=form.email.data).first()
        if existing_user is None:
            url = ServiceCaller()
            user = {
                "email": form.email.data,
                "username": form.username.data,
                "password": form.password.data}
            logging.info(f'web ::: calling service auth ::: add_user')
            r = url.call_post_on_service(user_data=user,
                                               service="auth",
                                               endpoint="add_user",
                                               api_version="v1",
                                               https=False)
            # user created
            if r.json()["code"] == "201":
                flash(f"""{form.username.data} activate your account to finish signing up.
                We have sent you a welcome email with an activation link to {form.email.data}. \n
                The activation link would stay active for 15 minutes.""")

                return redirect(url_for('auth_bp.login'))
            else:
                flash("Signup failed")
                return redirect(url_for('auth_bp.login'))
        flash('A user already exists with that email address.')
    return render_template('signup.html',
                           title='Create an Account.',
                           form=form,
                           template='signup-page',
                           body="Sign up for a user account.")

services/web/src/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

services/web/src/templates/all_notes.html
{% extends "base.html" %}

{% block content %}
<br>
<!--<div class="container-fluid">-->
<div class="container">
    {% if notes %}
    {% for note in notes %}
    <div class="card">
        <div class="card-header">
            {{ note.subject }}
        </div>
        <div class="card-body">
            <h4 class="card-title"><p style="color: orange"><strong>{{ note.topic }}</strong></p></h4>
            <h7><p class="text-muted">{{note.created}}</p></h7>
            <p class="card-text">{{ note.text|safe }}</p>
            {% if note.url|length %}
            <a href="{{ note.url }}" class="btn btn-primary"><i class="fa fa-cloud" aria-hidden="true"></i> Go to
                URL</a>
            {% else %}
            {% endif %}
            <a href="{{ url_for('edit_note', id=note.id, alt_id=current_user.alternative_id) }}"
               class="btn btn-info"><i
                    class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</a> &nbsp;&nbsp; &nbsp;&nbsp;
            <a href="{{ url_for('delete', id=note.id, alt_id=current_user.alternative_id) }}"
               class="btn btn-danger"><i
                    class="fa fa-trash" aria-hidden="true"></i> Delete</a>
        </div>
        <div class="card-footer text-muted">
            Repeat at: {{ note.repeat_at }}
        </div>
    </div>
    <br>
    {% endfor %}
    {% else %}
    <div class="card text-white bg-warning mb-3" style="max-width: 18rem;">
        <div class="card-body">
            <p class="card-text"><h5>아직 메모를 작성하지 않았습니다.<a
                href="{{ url_for('create_note', alt_id=current_user.alternative_id) }}">여기를 클릭하여</a> 추가하십시오.
        </h5></p>
        </div>
    </div>
    <br>
    <img src="https://sfigiel-ryanote.s3.eu-central-1.amazonaws.com/ryan1.PNG" alt="s3 error">
    {% endif %}

</div>
{% endblock %}

services/web/src/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


    <title>Hello, notes!</title>
    <link rel="shortcut icon" href="https://sfigiel-ryanote.s3.eu-central-1.amazonaws.com/favicon_ryan.ico">
    <!--    <link rel="stylesheet" href="{{ url_for('static', filename='css/cover.css') }}">-->
</head>
<!--<body style="background-color:#FFD700;">-->
<body>
<!--<body background="{{ url_for('static', filename='homepage.png') }}">-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <a class="navbar-brand" href="{{ url_for('homepage') }}">Ryanote</a>
    <div id="navbarNavDropdown" class="navbar-collapse collapse">
        <ul class="navbar-nav mr-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('create_note', alt_id=current_user.alternative_id) }}"><i
                        class="fa fa-plus-square" aria-hidden="true"></i> 메모 만들기</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('get_all_notes', alt_id=current_user.alternative_id) }}"><i
                        class="fa fa-binoculars" aria-hidden="true"></i> 모든 메모
                    보여주기</a>
            <li class="nav-item">
<!--                <a class="nav-link" href="{{ url_for('send_email_notes_manual_to_all', alt_id=current_user.alternative_id) }}"><i-->
<!--                        class="fa fa-envelope" aria-hidden="true"></i>-->

<!--                    리콜 할 메모가 포함 된 이메일을 보냅니다 (있는 경우)</a>-->
                            <a class="nav-link" href="{{ url_for('send_email_notes_manual_to_single_user', alt_id=current_user.alternative_id) }}"><i
                        class="fa fa-envelope" aria-hidden="true"></i>

                    메모가 포함 된 이메일 보내기</a>
                {% else %}
                {% endif %}

            </li>

        </ul>
        <ul class="navbar-nav">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href=""><i class="fa fa-user-circle" aria-hidden="true"></i> {{
                    current_user.username }}</a>
            </li>
            <br>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('logout', alt_id=current_user.alternative_id) }}"><i
                        class="fa fa-eraser" aria-hidden="true"></i> Logout</a>
            </li>
            {% else %}

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth_bp.login') }}"><i class="fa fa-fw fa-user"></i>Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth_bp.signup') }}"><i class="fa fa-plus-square"
                                                                                  aria-hidden="true"></i> Register</a>
                </li>
            </ul>
            {% endif %}
        </ul>
    </div>
</nav>

<br>

{% block content %}
{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<!-- JS, Popper.js, and jQuery -->
<!--<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"-->
<!--        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"-->
<!--        crossorigin="anonymous"></script>-->
<!--<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"-->
<!--        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"-->
<!--        crossorigin="anonymous"></script>-->
<!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"-->
<!--        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"-->
<!--        crossorigin="anonymous"></script>-->
</body>

<!--{% block footer %}-->
<!--<footer id="sticky-footer" class="py-4 bg-dark text-white-50">-->
<!--    <div class="container text-center">-->
<!--        <small>Copyright {{ now.year }} &copy; SF</small>-->
<!--    </div>-->
<!--</footer>-->
<!--{% endblock %}-->

<!--&lt;!&ndash; Footer &ndash;&gt;-->
<!--<footer class="page-footer font-small blue">-->

<!--  &lt;!&ndash; Copyright &ndash;&gt;-->
<!--  <div class="footer-copyright text-center py-3">© 2020 Copyright:-->
<!--    <a href="https://kimchimari.com/korean-potato-side-dish-gamja-jorim/"> 감자조림.com</a>-->
<!--  </div>-->
<!--  &lt;!&ndash; Copyright &ndash;&gt;-->

<!--</footer>-->
<!--&lt;!&ndash; Footer &ndash;&gt;-->
</html>

services/web/src/templates/change_password.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
<div class="container">
    <div class="row align-items-center justify-content-center">
        <div class="col-md-4">
            <h3>Set a new password</h3>
            <form action="{{ url_for('new_password', alternative_id=alternative_id, activate_token=activate_token) }}" method="POST" class="form" role="form">
                {{ form.csrf_token() }}
                <d1>
                {{ wtf.form_field(form.password, class='form-control') }}
                {{ wtf.form_field(form.confirm, class='form-control') }}
                    <br>
                    {{ form.recaptcha }}
                </d1>
                <br>
                <p><input type=submit class='btn btn-warning btn-block'>
                <hr>
            </form>
        </div>
    </div>
</div>
{% endblock %}

services/web/src/templates/cron2.html
{% extends "base.html" %}

{% block content %}


<div class="container">
    <ul class="list-group">
        {{data}}
        {% for note in data %}
        NOTE
        <li class="list-group-item">Topic: {{note.Notes.topic}}</li>
        <li class="list-group-item">URL: {{note.Notes.url}}</li>
        <li class="list-group-item">Subject: {{note.Notes.subject}}</li>
        <li class="list-group-item">Text: {{note.Notes.text}}</li>
        <li class="list-group-item">ID: {{note.Notes.id}}</li>
        <li class="list-group-item">Email: {{note.Users.email}}</li>
        <br>
        <li class="list-group-item">Alt_id: {{note.Users.alternative_id}}</li>
        <a href="{{ url_for('get_note', note_id=note.Notes.id, topic=note.Notes.topic) }}" class="btn btn-info"><i class="fa fa-trash" aria-hidden="true"></i> Show note</a>
        {% endfor %}
    </ul>
</div>

{% endblock %}

services/web/src/templates/dashboard.html
{% extends "base.html" %}

{% block content %}
siema
{% endblock %}

services/web/src/templates/edit_note.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
<div class="container">
    <div class="row align-items-center justify-content-center">
        <div class="col-md-8">
            <h3>Edit note</h3>
            <form action="{{ url_for('edit_note', id=note.id, alt_id=current_user.alternative_id) }}" method="POST"
                  class="form" role="form">
                {{ form.csrf_token() }}
                <d1>
                    {{ wtf.form_field(form.topic, class='form-control', value=note.topic) }}
                    {{ wtf.form_field(form.subject, class='form-control', value=note.subject) }}
                    {{ wtf.form_field(form.url, class='form-control', value=note.url) }}
                    {{ ckeditor.create(value=note.text) }}
                    {{ ckeditor.load() }}
                    {{ ckeditor.config(name='text') }}
                    {{ wtf.form_field(form.repeat_at, class='form-control', value=note.repeat_at) }}
                    {{ wtf.form_field(form.created, class='form-control', value=note.created) }}
                    <br>
                </d1>
                <br>
                <p><input type=submit class='btn btn-warning btn-block'>
                <hr>
            </form>
        </div>
    </div>
</div>
{% endblock %}

services/web/src/templates/get_note.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    <div class="card">
        <h5 class="card-header">{{data.subject}}</h5>
        <div class="card-body">
            <h4 class="card-title"><p style="color: orange"><strong>{{ data.topic }}</strong></p></h4>
            <p class="card-text">{{data.text|safe}}
                <br>
                <br>
                {% if data.url|length %}
                <a href="{{ data.url }}" class="btn btn-primary"><i class="fa fa-cloud" aria-hidden="true"></i> Go to
                    URL</a>
                {% else %}
                {% endif %}
                  <a href="{{ url_for('edit_note', id=data.id, alt_id='a49ec75dcfb246a79cfd27664849bd9a') }}" class="btn btn-info"><i
                    class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit note</a>
            </p>
            {% if data.repeat_at <= today %}
                     <a href="{{ url_for('postphone_note', note_id=data.id, topic=data.topic, days=1) }}"
               class="btn btn-success">1 day</a>
            <a href="{{ url_for('postphone_note', note_id=data.id, topic=data.topic, days=5) }}"
               class="btn btn-success">5 days</a>
            <a href="{{ url_for('postphone_note', note_id=data.id, topic=data.topic, days=14) }}" class="btn btn-warning">14
                days</a>
            <a href="{{ url_for('postphone_note', note_id=data.id, topic=data.topic, days=30) }}" class="btn btn-dark">30
                days</a>
               <a href="{{ url_for('postphone_note', note_id=data.id, topic=data.topic, days=90) }}" class="btn btn-dark">90
                days</a>
            {% else %}
            <br>
            <h6>Next repeat at {{data.repeat_at}}</h6>
            {% endif %}
        </div>
    </div>
    <br>
    <img src="https://sfigiel-ryanote.s3.eu-central-1.amazonaws.com/ryan.png" class="rounded-circle" width="400"
         height="400">
</div>
{% endblock %}

services/web/src/templates/homepage.html
{% extends "base.html" %}

{% block content %}
<!--<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">-->

<body background="{{ url_for('static', filename='homepage.png') }}">

<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">G'day mate !</h1>
        <p class="lead">Welcome to Ryanote, this the tool which you were waiting for.
            Thanks Ryanote you would be able to create notes afterwards our super intelligent algorithm would bring them back
            just in time</p>
        <hr class="my-4">
        {% if current_user.is_authenticated %}
        <p>Go back to You dashboard</p>
        <a class="btn btn-primary btn-lg" href="{{ url_for('get_all_notes', alt_id=current_user.alternative_id) }}" role="button">All notes</a>
        {% else %}
        <p>Don't have an account?</p>
        <a class="btn btn-primary btn-lg" href="{{ url_for('auth_bp.signup') }}" role="button">Register</a>
        {% endif %}
    </div>
</div>
{% endblock %}

services/web/src/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
<div class="form-wrapper">

    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    <div class="row align-items-center justify-content-center">
        <div class="col-md-4">
            <h3>Log In</h3>
            <form method="POST" action="/notes/login">
                {{ form.csrf_token }}
                {{ wtf.form_field(form.email, class='form-control') }}
                {{ wtf.form_field(form.password, class='form-control') }}
                <br>
                <p><input type=submit class='btn btn-warning btn-block'>
                <hr>


                <div class="login-signup">
                    <span>Don't have an account? <a href="{{ url_for('auth_bp.signup') }}">Sign up.</a> <br>Forgot password? Click <a href="{{ url_for('request_change_password') }}">here</a> to create a new one.</span>
                </div>

            </form>
        </div>
        <img src="https://sfigiel-ryanote.s3.eu-central-1.amazonaws.com/apeach_muzi.jpg" class="rounded-circle" width="400"
             height="400">
    </div>
</div>
{% endblock %}

services/web/src/templates/notes.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}


{% block content %}

<div class="container">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul class=flashes>
        {% for message in messages %}
        <div class="alert bg-warning alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    <div class="row align-items-center justify-content-center">
        <div class="col-md-8">
            <h3>Add a new note</h3>
            <form action="{{ url_for('create_note', alt_id=current_user.alternative_id) }}" method="POST" class="form"
                  role="form">
                {{ form.csrf_token() }}
                <d1>
                    {{ wtf.form_field(form.topic, class='form-control', placeholder='first of all put some topic') }}
                    {{ wtf.form_field(form.subject, class='form-control') }}
                    {{ wtf.form_field(form.url, class='form-control', placeholder='maybe URL ?') }}
                    {{ ckeditor.create() }}
                    {{ ckeditor.load() }}
                    {{ ckeditor.config(name='text') }}
                    {{ wtf.form_field(form.created, class='form-control') }}
                    <br>
<!--                    {{ form.recaptcha }}-->
                </d1>
                <br>
                <p><input type=submit class='btn btn-warning btn-block'>
                <hr>
            </form>
<!--            <img src="{ url_for('static', filename='ryandance.PNG') }}" width="100" height="150">-->
            <img src="https://sfigiel-ryanote.s3.eu-central-1.amazonaws.com/ryandance.PNG" width="100" height="150">
        </div>
    </div>
</div>
<br>
<div class="container">
    {% for note in notes %}
    <div class="card">
        <div class="card-header">
            {{ note.subject }}
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ note.topic }}</h5>
            <p class="card-text">{{ note.text|safe }}</p>
            <!--            {% if note.url|length %}-->
            <!--            <a href="{{ note.url }}" class="btn btn-primary">Go to URL</a>-->
            <!--            {% else %}-->
            <!--            {% endif %}-->
            <!--            <a href="{{ url_for('delete', id=note.id, alt_id=current_user.alternative_id) }}" class="btn btn-danger">Delete</a>-->
            <!--            <a href="{{ url_for('edit_note', id=note.id, alt_id=current_user.alternative_id) }}" class="btn btn-info">Edit</a>-->
        </div>
        <div class="card-footer text-muted">
            Repeat: {{ note.repeat_at }}
        </div>
    </div>
    <br>
    {% endfor %}
</div>
{% endblock %}

services/web/src/templates/reset_password.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
<div class="form-wrapper">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    <div class="row align-items-center justify-content-center">
        <div class="col-md-4">
            <h3>Reset password</h3>
            <form action="{{ url_for('request_change_password') }}" method="POST" class="form"
                  role="form">
                {{ form.csrf_token() }}
                <d1>
                    {{ wtf.form_field(form.email, class='form-control', placeholder='ryan_89@gmail.com') }}
                    <br>
                    {{ form.recaptcha }}
                </d1>
                <br>
                <p><input type=submit class='btn btn-warning btn-block'>
                <hr>
            </form>
            <img src="https://sfigiel-ryanote.s3.eu-central-1.amazonaws.com/ryandance.PNG" width="100" height="150">
        </div>
    </div>
</div>
{% endblock %}

services/web/src/templates/signup.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}

{% block content %}
<div class="form-wrapper">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <i class="fa fa-commenting-o" aria-hidden="true"></i> {{ message }}
    </div>
    {% endfor %}
    <div class="row align-items-center justify-content-center">
        <div class="col-md-4">
            <h3>Sign Up</h3>
            <form method="POST" action="/notes/signup">
                {{ form.csrf_token }}
                {{ wtf.form_field(form.username, class='form-control', placeholder='Ryan_89') }}
                {{ wtf.form_field(form.email, class='form-control', placeholder='ryan_89@gmail.com') }}
                {{ wtf.form_field(form.password, class='form-control') }}
                {{ wtf.form_field(form.confirm, class='form-control') }}
                <br>
<!--                {{ form.recaptcha }}-->
                <br>
                <p><input type=submit class='btn btn-warning btn-block'>
                <hr>
            </form>

            <div class="login-signup">
                <span>Already have an account? <a href="{{ url_for('auth_bp.login') }}">Log in.</a></span>
            </div>
        </div>
        <img src="https://sfigiel-ryanote.s3.eu-central-1.amazonaws.com/apeach_muzi.jpg" class="rounded-circle" width="400"
             height="400">
    </div>
</div>
{% endblock %}

services/web/src/templates/test_template.html
<br>
<br>
{{q}}
<br>
<br>
{{q.Users.id}}
<br>
<br>
{{q.ActivationToken.id}}
<br>
<br>